name: Deployment Workflow

on:
   push:
      branches:
         - main

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - name: Testing the app
           run: |
             cd my-app
             npm test