name: Deployment Workflow

on:
   push:
      branches:
         - main

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - name: Checking out code
           uses: actions/checkout@v4
         
         - name: Setup node
           uses: actions/setup-node@v3
           with:
            node-version: "20"
         
         # - name: Installing the dependencies
         #   run: npm install

         - name: Running tests
           run: npm test