name: Testing Action Runner

on:
   push:
      branches:
         main

jobs:
   testing:
      runs-on: ubuntu-latest

      steps:
         - name: Checking out code
           uses: actions/checkout@v4

         - name: Installing dependencies
           run: npm run install

         - name: Running command 'pwd'
           run: pwd

         - name: Running command 'ls -a'
           run: ls -a